#!/bin/bash
# This script should spin up the specified version of Tor

ARRAY=(directory1 directory2 directory3 node1 node2 node3 node4 node5 node6 node7 node8 node9 client server)
POINT=0

while [ $POINT -lt 14 ]; do
  FILE=${ARRAY[$POINT]}
  if [ ! -e tmp/$FILE ]; then
    echo "Starting ${FILE}..."
    echo 'Begin ${FILE} Log' > tmp/$FILE
    sudo -u mininet /home/mininet/tor/$FILE/bin/tor > /home/mininet/tor/tmp/$FILE &
    break 2
  else
    POINT=$((POINT+1))
  fi
done
