language: c
before_script: ./autogen.sh
compiler:
  - clang
  - gcc
branches:
  only:
    - master
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq autotools-dev pkg-config hardening-wrapper automake autoconf libtool
script: ./configure && make
